import { StyleSheet } from 'react-native';
import { verticalScale } from 'react-native-size-matters';
import { PADDING_HORIZONTAL, scale } from '../../helpers/demensions';

export const styles = StyleSheet.create({
  monitoring: {
    paddingBottom: verticalScale(20),
    paddingHorizontal: PADDING_HORIZONTAL,
    marginTop: verticalScale(15),
    alignContent: 'center',
  },
  monitorings: {
    flexDirection: 'column',
    justifyContent: 'center',
    borderColor: '#fff',
    width: '100%',
  },
  title: {
    textTransform: 'uppercase',
    marginBottom: verticalScale(20),
    fontWeight: '800',
    fontSize: scale(26),
    color: '#FFD700', // Gold color for title
    textAlign: 'center',
    letterSpacing: 1,
    textShadowColor: 'rgba(255, 215, 0, 0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  body: {
    width: '100%',
    marginBottom: verticalScale(15),
    borderRadius: scale(15),
    backgroundColor: '#1A1A1A',
    shadowColor: "#FFD700",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 8,
  },
  item: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    borderRadius: scale(15),
    paddingHorizontal: scale(20),
    paddingVertical: verticalScale(40),
    borderWidth: 2,
    borderColor: '#FFD700', // Gold border
    backgroundColor: '#121212',
  },
  bonusLinear: {
    position: 'absolute',
    top: -verticalScale(12),
    right: scale(10),
    paddingHorizontal: scale(15),
    paddingVertical: verticalScale(5),
    borderRadius: scale(5),
    backgroundColor: '#FFD700',
    zIndex: 10,
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  bonus: {
    fontSize: scale(14),
    fontWeight: '900',
    color: '#000',
    textTransform: 'uppercase',
  },
  content: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    width: '100%',
  },
  anims: {
    width: verticalScale(160),
    height: verticalScale(160),
    overflow: 'hidden',
    borderRadius: scale(160) / 2,
    borderWidth: 3,
    borderColor: '#FFD700',
    marginBottom: verticalScale(20),
    shadowColor: "#FFD700",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  animsEmpty: {
    width: verticalScale(160),
    height: verticalScale(160),
    overflow: 'hidden',
    borderRadius: verticalScale(160) / 2,
  },
  anim: {},
  info: {
    width: '100%',
    marginTop: verticalScale(10),
    alignItems: 'center',
  },
  subtitle: {
    color: '#FFD700',
    fontSize: scale(24),
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: verticalScale(5),
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  static: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: verticalScale(5),
  },
  online: {
      color: '#FFD700',
  },
  subOnline: {
      color: '#AAA',
  },
});
